Backend module issue
scutl-runbook/runbook pull request #15
Opened 2022-09-23 09:56 UTC by JunkyLove

2022-09-23 12:17 UTC, Lingchao-Zhang commented on frontend/src/PlayBookComponents/RunBookModule.tsx
> +export default RunBookModule;
Thanks for revising my typo!

2022-09-23 12:21 UTC, Lingchao-Zhang commented on runbook/views.py
> +        try:
I wonder that how new module can be saved in corresponding runbook? I think you just created a new module, but you didn't save it to the corresponding runbook. Maybe you need to get the runbook which you want to create a module, then create a new module and add this module to modules of this runbook

2022-09-23 12:25 UTC, Lingchao-Zhang commented on runbook/views.py
> +                module.save()
I think update_module function has already changed module so that module.save() may not be needed.

2022-09-23 12:31 UTC, Lingchao-Zhang reviewed
Good job for module parts in backend.
I gave some feedback on some parts.

2022-09-24 01:11 UTC, Mark-Fenng requested changes

2022-09-24 01:11 UTC, Mark-Fenng commented on runbook/views.py
> +        try:
Just like 'runbook''s post method, this method receives a 'runbookId' param, and then adds a new module to it.

2022-09-24 01:11 UTC, Mark-Fenng commented on runbook/views.py
> +                module.save()
I think they found a bug in my previous code. I'll fix it later.
After updating editTimestamp, we do need to save it.

2022-09-24 01:11 UTC, Mark-Fenng commented on runbook/views.py
> +            new_module.save()
```suggestion
```
The createTimestamp can be generated by the database automatically.

2022-09-25 02:40 UTC, Leavaway commented
I've updated post method and url.py

2022-09-25 03:54 UTC, JunkyLove commented on runbook/serializers.py
> +        "modules": str([serialize_module(module) for module in runbook_model.modules.all()]),
Thank you for your reviwing and I finally grasped the depth parameter. I have fixed it

2022-09-25 04:52 UTC, Mark-Fenng approved these changes

2022-09-25 04:52 UTC, merged